# Requirements
<!-- 
An idea of what is required to make the project actually happen
-->

## People
<!--
Who needs to be involved, what's the proposed structure, what will it take to get their involvement?
-->

My employer is using the probaverse quite often, because we do a lot of probabilistic modelling. Now that we are writing a Canada-wide manual on "how to conduct a flood frequency analysis in Canada", we are wanting to include the probaverse in our worked examples, so there is interest in getting the software on CRAN. It sounds like BGC will be contributing some money, but not enough to get the required functionality on CRAN. With the help of the ISC, I can make this software live.

I would like to get the feedback of ROpenSci early. I'll bring them on right away if I know I'll have dedicated tie to work on the project. As mentioned, I would also appreciate the help of the ISC to get other reviewers, and possibly additional help. 

## Processes
<!-- 
What processes need to be put in place e.g. codes of conduct, regular ISC meetings, handover to the community at large?
-->

Standard code of conduct is adopted.

Regular ISC meetings (or review meetings in general) would be nice.

No "handover" but rather I will continue to develop the probaverse and (more than) welcome contributors.

## Tools & Tech
<!--
What is going to be needed to deliver this project? 

Will cloud computing be used - if yes are there are necessary components that will be deciding factors between providers?

Are there tools or tech that don't exist that will be produced to facilitate the project?
-->

I'm all set here already:

- I am already paying for [probaverse.com](https://probaverse.com), and will move the package websites under that domain.
- I am using GitHub for development.

## Funding
<!-- 
[TO DO] THE GUIDANCE IS PRETTY UNCLEAR, ESP IN LIGHT OF GABOR'S PROPOSAL VS AWARD SIZE

-->

I'm asking for \$14,000 CAD.

That will cover 10 hours of work per week for 7 weeks, at \$200 per hour.


## Summary
<!--
A summary of the requirements that contextualises the costs
-->

There are two areas where help from the ISC would be great.

1. A lack of breathing room has also meant that the probaverse has been sheltered from the wider community since its inception in early 2020. I would appreciate help in _getting_ help from others and broadcasting the probaverse to the wider community.

2. Ultimately I need to be able to set aside time to work on this project. I hardly have "free time" as a working dad, either. With a financial contribution from the ISC, I will go on reduced hours at work to get this project done.
