# Signatories
<!-- 
This section provides the ISC with a view of the support received from the community for a proposal. Acceptance isn't predicated on popularity but community acceptance is important.  Willingness to accept outside input is also a good marker for project delivery. 

An optional section would be for R-Core signatories where changes to R are proposed.
-->

## Project team
<!-- 
Who are the people responsible for actually delivering the project if the proposal gets accepted and are already signed up and rearing to go?
-->

I (Vincenzo Coia) will be the person to actually deliver the project. You can learn more about me by visiting https://vincenzocoia.com/, but here's a summary of relevant information.

### Summary of my background

- **2012-2017**: PhD in statistics from The University of British Columbia (UBC)
- **2017-2022**: Teach data science at UBC, including [STAT 545](https://stat545.stat.ubc.ca/) (Jenny Bryan's famous R course), eventually ending up as Assistant Professor of Teaching.
- **2022-present**: work at BGC Engineering Inc. as a data scientist modelling geohazards.

### Summary of relevant skills

- Expert in designing and writing R packages, especially around grammars. Demonstrated packages in addition to the probaverse include: 
    - [igcop](https://igcop.netlify.app/), which is on CRAN and has a C++ backend (this one is not a grammar).
    - [sxchan](https://stochagbem.github.io/sxchan/), provides a grammar for working with river channel cross sections in R (will be submitted to CRAN once a dependency is accepted to CRAN, which is pending).
    - [gbem](https://stochagbem.github.io/gbem/), provides a grammar for eroding a river channel (depends on sxchan; will submit once Ferguson's equation is implemented as an alternative to Manning's).
    - [stochasim](https://stochagbem.github.io/stochasim/), provides a grammar modelled after **purrr** for iterating flood events through a channel (under development).
- Expert in applying R to advanced applications, including expert use of the tidyverse and rlang.
- Expert in statistics (PhD), particularly in probabilistic and dependence modelling.

## Contributors
<!-- 
Who are the people who have actively helped with this proposal but won't necessarily be on the core project team later?
-->

I put this proposal together myself. 

## Consulted
<!-- 
Who has been given the opportunity to provide feedback on the proposal? This should include any R Consortium & ISC members who the proposal has been discussed with.
-->

I decided pretty late to put together a proposal, so nobody was consulted. 